# package(default_visibility=["//visibility:public"])

cc_library(
    name = "double_buffer",
    hdrs = ["double_buffer.h"],
    includes = [","],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_jbeder_yaml_cpp//:yaml-cpp",
    ],
)